print("Hello, welcome to Adriana Machado's encryption/decryption machine. What is your name?")
x = input()
print("Nice to meet you, ", x, ". I am a non-sentient machine; you can call me Arendt.")
print("Please enter in ALL CAPS any variation of the English 26-letter alphabet with no punctuation and watch the magic occur!")
y = input()



p = 13
q = 17
n = p * q # public key
e = 5 # public key
i = 2



def f(n):
    
    """phi function of n
    Argument: n
    Output: p*q-p-q+1"""
    
    return int((p - 1)*(q - 1))



d = int(((i * f(n)) + 1) / e) # private key



print("Your phi(n) is: ", f(n))



caps_alpha = {"A":1, "B":2, "C":3, "D":4, "E":5, "F":6, "G":7, "H":8, "I":9, "J":10, "K":11, "L":12, "M":13, "N":14, "O":15, "P":16, "Q":17, "R":18, "S":19, "T":20, "U":21, "V":22, "W":23, "X":24, "Y":25, "Z":26, " ":27}
num_caps_alpha = {1:"A", 2:"B", 3:"C", 4:"D", 5:"E", 6:"F", 7:"G", 8:"H", 9:"I", 10:"J", 11:"K", 12:"L", 13:"M", 14:"N", 15:"O", 16:"P", 17:"Q", 18:"R", 19:"S", 20:"T", 21:"U", 22:"V", 23:"W", 24:"X", 25:"Y", 26:"Z", 27:" "}



def cypher(y):
    
    """
    For processing letters to numbers through the caps_alpha cypher. 
    
    Argument: ALL CAPS series of letters
    Output: a list of numbers corresponding to each original letter
    """
    
    l_to_n = []
    for letter in y:
        number = caps_alpha.get(letter)
        l_to_n.append(number)
    return l_to_n

cypher = cypher(y)



print("Your cypher is: ", cypher)



def c_encryption(cypher):
    
    """
    For processing the list of numbers generated by the cypher through the given encryption formula
    Argument: cypher output list of numbers
    Output: list of encrypted numbers
    """
    
    c_to_e = []
    for number in cypher:
        c = int((number**e)%n)
        c_to_e.append(c)
    return c_to_e

encryption = c_encryption(cypher)



print("Your encryption is: ", encryption)



def e_decryption(encryption):
    
    """
    To return the decrypted list of integers representing the cyphered user input
    Argument: encryption list
    Output: cypher list"""
    
    e_to_d= []
    for number in encryption:
        decrypted = int((number**d)%n)
        e_to_d.append(decrypted)
        
    return e_to_d

decryption = e_decryption(encryption)



print("Your decryption is: ", decryption)
print("For reference, your cypher was: ", cypher)
if decryption == cypher:
    print("They match! Hurray!")
if decryption != cypher:
    print("Woops, something went wrong...")



def reverse_cypher(decryption):
    
    """To send the decrypted message back through the cypher and get the original message as a string
    Argument: Decryption list
    Output: Decyphered list"""
    
    d_to_l = []
    for int in decryption:
        letter = num_caps_alpha.get(int)
        d_to_l.append(letter)
    return d_to_l

r_cypher = reverse_cypher(decryption)



cypher_string = ""
print("Your original input text was: ", cypher_string.join(r_cypher))
print("ET VOILÀ!!!")
